name: mercado_zap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0    # alterado para versão compatível
  path_provider: ^2.1.5
  google_maps_flutter: ^2.14.0
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  cloud_firestore: ^6.1.1
  uuid: ^4.5.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13    # downgrade para ser compatível com hive_generator
  hive_generator: ^2.0.1   # versão compatível com build_runner 2.4.x
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo/logo01.png
    - lib/assets/banner/image1.png
    - lib/assets/banner/image2.jpg
    - lib/assets/banner/image3.png
    - lib/assets/banner/image4.png
    - lib/assets/banner/baixados.jpg
