// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqwZqUvZy-tYPhoT9jdwQ27quje2F5Hq0',
    appId: '1:110294184764:web:9ea7f06e0ee2bea05b6439',
    messagingSenderId: '110294184764',
    projectId: 'mercado-zap-45dca',
    authDomain: 'mercado-zap-45dca.firebaseapp.com',
    storageBucket: 'mercado-zap-45dca.firebasestorage.app',
    measurementId: 'G-EY44M4NSRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3ygo0FbIbckl-DpY_g6engjR9OTGqcE',
    appId: '1:110294184764:android:1f74b3f450e75b455b6439',
    messagingSenderId: '110294184764',
    projectId: 'mercado-zap-45dca',
    storageBucket: 'mercado-zap-45dca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAAIGPTG2Q-FSlKAoyyboOPxMk_WeBaBo',
    appId: '1:110294184764:ios:08ca231c0df4bb7f5b6439',
    messagingSenderId: '110294184764',
    projectId: 'mercado-zap-45dca',
    storageBucket: 'mercado-zap-45dca.firebasestorage.app',
    iosBundleId: 'com.example.mercadoZap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAAIGPTG2Q-FSlKAoyyboOPxMk_WeBaBo',
    appId: '1:110294184764:ios:08ca231c0df4bb7f5b6439',
    messagingSenderId: '110294184764',
    projectId: 'mercado-zap-45dca',
    storageBucket: 'mercado-zap-45dca.firebasestorage.app',
    iosBundleId: 'com.example.mercadoZap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqwZqUvZy-tYPhoT9jdwQ27quje2F5Hq0',
    appId: '1:110294184764:web:e0007b6eeee0edfc5b6439',
    messagingSenderId: '110294184764',
    projectId: 'mercado-zap-45dca',
    authDomain: 'mercado-zap-45dca.firebaseapp.com',
    storageBucket: 'mercado-zap-45dca.firebasestorage.app',
    measurementId: 'G-18M75180VM',
  );
}
